name: Deploy Vite App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Project
        run: npm run build

      - name: Clear Old Files on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WEBANATOMYURL }}
          username: ${{ secrets.WEBANATOMYSSHUSER }}
          key: ${{ secrets.WEBANATOMYSSHKEY }}
          port: 65002
          script: |
            rm -rf /home/u466434331/public_html/web*

      - name: Upload New Build Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WEBANATOMYURL }}
          username: ${{ secrets.WEBANATOMYSSHUSER }}
          key: ${{ secrets.WEBANATOMYSSHKEY }}
          port: 65002
          source: "dist/"
          target: "/home/u466434331/public_html/web"